CC = gcc
CFLAGS = -Wall -pedantic -ansi -g
OBJ = main.o readFile.o sorter.o 
EXEC = sss

$(EXEC) : $(OBJ)
	$(CC) $(OBJ) -o $(EXEC)

main.o : main.c sorter.h readFile.h
	$(CC) -c main.c $(CFLAGS)

sorter.o : sorter.c readFile.h
	$(CC) -c sorter.c

readFile.o : readFile.c readFile.h sorter.h
	$(CC) -c readFile.c 

clean :
	rm -f $(EXEC) $(OBJ)